"""empty message

Revision ID: 70ce287469b5
Revises: a4dfdb9e9451
Create Date: 2022-11-11 14:47:05.096276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ce287469b5'
down_revision = 'a4dfdb9e9451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arenas', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('arena_location_key', 'arenas', type_='unique')
    op.drop_constraint('team_name_key', 'teams', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('team_name_key', 'teams', ['name'])
    op.create_unique_constraint('arena_location_key', 'arenas', ['location'])
    op.alter_column('arenas', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
