"""empty message

Revision ID: 06338f319ff6
Revises: 70ce287469b5
Create Date: 2022-11-15 23:57:48.329971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06338f319ff6'
down_revision = '70ce287469b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('players_last_name_btree', table_name='players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('players_last_name_btree', 'players', ['last_name'], unique=False)
    # ### end Alembic commands ###
